name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image backend
      run: docker build . --file DaprBackEnd/Dockerfile --tag mybackend:$(date +%s)
    - name: Build the docker image frontend
      run: docker build . --file DaprFrontEnd/Dockerfile --tag myfrontend:$(date +%s)
      
  
