name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    -
      name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      id: docker_build_backend
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: shafeer/mybackend:1.0.0.${{ github.run_number }}
        file: DaprBackEnd/Dockerfile
    -
      name: Build and push
      id: docker_build_frontend
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: shafeer/myfrontend:1.0.0.${{ github.run_number }}
        file: DaprFrontEnd/Dockerfile
    -  
      name: Build and push
      id: docker_build_backend2
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: shafeer/mybackend2:1.0.0.${{ github.run_number }}
        file: BackendWeather/Dockerfile
    - 
      name: frontend update
      uses: Azure/cli@v1.0.6
      with:
        # Specify the script here
        inlineScript: az containerapp update --name myfrontend --resource-group my-container-apps --image shafeer/myfrontend:1.0.0.${{ github.run_number }}
    - 
      name: backend update
      uses: Azure/cli@v1.0.6
      with:
        # Specify the script here
        inlineScript: az containerapp update --name mybackend --resource-group my-container-apps --image shafeer/mybackend:1.0.0.${{ github.run_number }}
    - 
      name: backend update
      uses: Azure/cli@v1.0.6
      with:
        # Specify the script here
        inlineScript: az containerapp update --name mybackend --resource-group my-container-apps --image shafeer/mybackend2:1.0.0.${{ github.run_number }}
